service: manage-lambda-layers

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true
  excludeDevDependencies: true
  include:
    - node_modules/**
    - src/**

custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules:
      forceExclude:
        - moment
      
provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  versionFunctions: false

functions:
  getCurrentDateTime:
    handler: src/functions/getCurrentDatetTime.handler
    name: ${self:service}-${self:provider.stage}-get-current-date-time
    events:
      - http:
          path: getCurrentDateTime
          method: get
          cors: true